### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by JinFeng-Wu** [iwyoo/Autoencoder3D#1]
Thank you very much for the 3D autoencoder code. I'm a new starter of tensorflow, I want to build a 3d autoencoder and convolutional neural network. It's a very confusing for me to understand how to use your code, can you give me some explanations about the code? Much appreciated.

**Comment by iwyoo** [comment]
Sorry for the missing test/example code. However, this code is not working well in my case. In addition, some of the part can be used, but some part is deprecated in the current TensorFlow. Partial use is fine, but full use is not recommended.
